"""add auth_sessions and ws_tickets tables

Revision ID: w3x4y5z6a7b8
Revises: v2w3x4y5z6a7
Create Date: 2026-07-16

Adds the two tables backing the P1.1a cookie-auth backend foundation:
`auth_sessions` (server-side refresh-token sessions with rotation + reuse
detection) and `ws_tickets` (single-use WebSocket auth tickets). Both are
additive-only; `downgrade()` drops them, which is safe since nothing else
references these tables yet (dark-shipped behind COOKIE_AUTH_MODE=bearer).

Hand-written (not autogenerated) per plan Task 1 GOTCHA: autogenerate against
this schema would also emit unrelated ORM/live-schema drift (see
docs/remediation/preflight-evidence-and-designs.md §8 — broadcasts/districts/
provinces/sub_districts drift) that is out of scope for this migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "w3x4y5z6a7b8"
down_revision: Union[str, None] = "v2w3x4y5z6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(connection, table_name: str) -> bool:
    return sa.inspect(connection).has_table(table_name)


def upgrade() -> None:
    connection = op.get_bind()

    if not _has_table(connection, "auth_sessions"):
        op.create_table(
            "auth_sessions",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column(
                "user_id",
                sa.Integer(),
                sa.ForeignKey("users.id"),
                nullable=False,
            ),
            sa.Column("family_id", sa.String(length=36), nullable=False),
            sa.Column("token_hash", sa.String(length=64), nullable=False),
            sa.Column(
                "status",
                sa.String(length=16),
                nullable=False,
                server_default="active",
            ),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
            ),
            sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column(
                "replaced_by_id",
                sa.Integer(),
                sa.ForeignKey("auth_sessions.id"),
                nullable=True,
            ),
        )
        op.create_index(
            "ix_auth_sessions_user_id", "auth_sessions", ["user_id"]
        )
        op.create_index(
            "ix_auth_sessions_family_id", "auth_sessions", ["family_id"]
        )
        op.create_index(
            "ix_auth_sessions_token_hash",
            "auth_sessions",
            ["token_hash"],
            unique=True,
        )

    if not _has_table(connection, "ws_tickets"):
        op.create_table(
            "ws_tickets",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column(
                "user_id",
                sa.Integer(),
                sa.ForeignKey("users.id"),
                nullable=False,
            ),
            sa.Column("token_hash", sa.String(length=64), nullable=False),
            sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
            ),
        )
        op.create_index("ix_ws_tickets_user_id", "ws_tickets", ["user_id"])
        op.create_index(
            "ix_ws_tickets_token_hash", "ws_tickets", ["token_hash"], unique=True
        )


def downgrade() -> None:
    connection = op.get_bind()

    if _has_table(connection, "ws_tickets"):
        op.drop_table("ws_tickets")

    if _has_table(connection, "auth_sessions"):
        op.drop_table("auth_sessions")
