"""add broadcasts table

Revision ID: y0z1a2b3c4d5
Revises: x9y0z1a2b3c4
Create Date: 2026-07-18

Creates the `broadcasts` table (and its two enum types) that the ORM model
`app.models.broadcast.Broadcast` has always declared but which no migration
ever created — a live-schema drift documented in
docs/remediation/preflight-evidence-and-designs.md §8. On PROD the broadcast
scheduler (app startup background task) polls `SELECT ... FROM broadcasts`
every ~15s and has been logging `UndefinedTableError: relation "broadcasts"
does not exist` on every cycle, per worker.

Hand-written (not autogenerated) on purpose: autogenerate against the current
ORM would also emit the other unrelated live-schema drift (districts /
provinces / sub_districts — same §8) that is out of scope here, exactly as the
`w3x4y5z6a7b8` auth-sessions migration noted.

Enum labels are the Python enum MEMBER NAMES (uppercase), not the `.value`
strings — SQLAlchemy's `Enum(PyEnumClass)` stores names by default (confirmed
by the runtime query casting `'SCHEDULED'::broadcaststatus`).

Additive + idempotent: `upgrade()` no-ops if the table already exists, and the
enum types are created with `checkfirst=True`, so re-running against a DB where
a previous partial/manual apply already made them is safe.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "y0z1a2b3c4d5"
down_revision: Union[str, None] = "x9y0z1a2b3c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# create_type=False: the enums are created/dropped explicitly below with
# checkfirst, so create_table must not try to CREATE TYPE them again.
broadcaststatus = postgresql.ENUM(
    "DRAFT",
    "SCHEDULED",
    "SENDING",
    "COMPLETED",
    "FAILED",
    "CANCELLED",
    name="broadcaststatus",
    create_type=False,
)
broadcasttype = postgresql.ENUM(
    "TEXT",
    "IMAGE",
    "FLEX",
    "MULTI",
    "OBJECT_REF",
    name="broadcasttype",
    create_type=False,
)


def _has_table(connection, table_name: str) -> bool:
    return sa.inspect(connection).has_table(table_name)


def upgrade() -> None:
    connection = op.get_bind()

    if _has_table(connection, "broadcasts"):
        return

    broadcaststatus.create(connection, checkfirst=True)
    broadcasttype.create(connection, checkfirst=True)

    op.create_table(
        "broadcasts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message_type", broadcasttype, nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_audience", sa.String(), nullable=True),
        sa.Column("target_filter", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", broadcaststatus, nullable=True),
        sa.Column("total_recipients", sa.Integer(), nullable=True),
        sa.Column("success_count", sa.Integer(), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_by",
            sa.Integer(),
            sa.ForeignKey("users.id"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
    )
    op.create_index("ix_broadcasts_id", "broadcasts", ["id"])
    op.create_index("ix_broadcasts_status", "broadcasts", ["status"])


def downgrade() -> None:
    connection = op.get_bind()

    if _has_table(connection, "broadcasts"):
        op.drop_index("ix_broadcasts_status", table_name="broadcasts")
        op.drop_index("ix_broadcasts_id", table_name="broadcasts")
        op.drop_table("broadcasts")

    broadcasttype.drop(connection, checkfirst=True)
    broadcaststatus.drop(connection, checkfirst=True)
